equinor/fusion-workspace

- .github/labeler.yml
Added the following tags to labeler;
workspace-core
workspace-react
I also change githubActions to be github-actions to match the naming convention
> add workspace-core, workspace-react to labeler

- packages/ag-grid/src/lib/components/Grid.tsx
- packages/ag-grid/src/lib/components/grid.styles.ts
Grid was set to fixed with but the width can be % values so it was set to 100%.
> Fix grid width not being auto

- packages/workspace-react/src/lib/classes/workspaceSidesheetController.ts
- packages/workspace-react/src/lib/classes/workspaceViewController.ts
- packages/workspace-react/src/lib/components/resizableSidesheet/ResizableSidesheet.tsx
- packages/workspace-react/src/lib/components/resizableSidesheet/index.ts
- packages/workspace-react/src/lib/components/resizableSidesheet/resizableSidesheet.styles.ts
- packages/workspace-react/src/lib/components/workspaceBody/WorkspaceBody.tsx
- packages/workspace-react/src/lib/components/workspaceBody/workspaceBody.styles.ts
- packages/workspace-react/src/lib/hooks/index.ts
- packages/workspace-react/src/lib/hooks/useIsSidesheetOpen.ts
- packages/workspace-react/src/lib/hooks/useSidesheetWidth.ts
- packages/workspace-react/src/lib/test/onSidesheetOpenOrClosed.spec.ts
- packages/workspace-react/src/lib/types/events.ts
Added a resizable container to hold the sidesheet component. Using the same package that was used in the Castberg portal
> add resizable container to hold sidesheet component

- package-lock.json
> Bump NPM 8.16.0

- package-lock.json
- package.json
> Remove react-virtual

- .github/workflows/ci.yml
- .github/workflows/prettier.yml
> add prettier action

- .github/workflows/prettier.yml
> Fix prettier action

- .github/labeler.yml
Added workspace-fusion to labeler for path packages/workspace-fusion
> add workspace-fusion to labeler

- packages/test-app/src/app/app.tsx
- packages/workspace-fusion/src/lib/classes/fusionWorkspaceBuilder.tsx
- packages/workspace-fusion/src/lib/utils/addViewController.ts
- packages/workspace-react/src/lib/classes/workspaceViewController.ts
- packages/workspace-react/src/lib/components/ActionBar/ActionBar.tsx
- packages/workspace-react/src/lib/components/ActionBar/actionBar.styles.ts
- packages/workspace-react/src/lib/components/ActionBar/index.ts
- packages/workspace-react/src/lib/components/AppNameHeader/AppNameHeader.tsx
- packages/workspace-react/src/lib/components/AppNameHeader/appNameHeader.styles.ts
- packages/workspace-react/src/lib/components/AppNameHeader/index.ts
- packages/workspace-react/src/lib/components/workspaceHeader/WorkspaceHeader.tsx
Added appKey to header like in castberg
-   [x] My code is easy to read.
-   [x] Documentation and …
> add appkey to header of workspace

- packages/test-app/src/app/app.tsx
- packages/test-app/src/app/mockData.ts
- packages/test-app/src/app/types.ts
- packages/test-app/src/app/workspaceConfig.tsx
- packages/workspace-fusion/src/lib/index.ts
- packages/workspace-fusion/src/lib/utils/createFusionWorkspace.tsx
- packages/workspace-fusion/src/lib/utils/index.ts
Check the example in app.tsx
The createFusionWorkspace now returns a () => JSX.Component;
-   [x] …
> Improve fusion app setup

- .github/workflows/ci.yml
> add legacy peer deps to fix react-virtual

- packages/test-app/src/app/app.tsx
- packages/workspace-fusion/src/lib/utils/createFusionWorkspace.tsx
- packages/workspace-fusion/src/lib/utils/fusionTabOrder.ts
Add a JS module for sorting tabs in fusion workspace
-   [x] My code is easy to read.
-   [x] …
> add fusion tab sorting

- packages/test-app/src/app/app.tsx
> add test app config

- packages/test-app/src/app/HandoverSidesheet/DetailsTab.tsx
- packages/test-app/src/app/HandoverSidesheet/HandoverSidesheet.tsx
- packages/test-app/src/app/app.tsx
- packages/test-app/src/app/workspaceConfig.tsx
> add testapp sidesheet

- packages/test-app/src/app/workspaceConfig.tsx
> Table config testapp

- packages/workspace-fusion/src/lib/classes/fusionWorkspaceBuilder.tsx
Loading spinner wasnt working in fusion workspace
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] My code is easy to read.
-   [ ] …
> fix loading spinner in fusion workspace view

- packages/data-source/src/lib/test/onDataChanged.spec.ts
> fix failing test datasource

- packages/test-app/src/app/app.tsx
- packages/test-app/src/app/workspaceConfig.tsx
- packages/workspace-fusion/src/lib/components/StatusBarWrapper.tsx
- packages/workspace-fusion/src/lib/types/configuration.ts
Status bar config had a weird interface, now it is a function that takes in data and returns an array of items
-   [ ] I have linked my DevOps task using …
> Change status bar config

- package-lock.json
- package.json
- packages/data-source/src/lib/test/onDataChanged.spec.ts
- packages/test-app/src/app/app.tsx
- packages/test-app/src/app/workspaceConfig.tsx
- packages/workspace-core/src/lib/classes/observable.ts
- packages/workspace-core/src/lib/classes/selectionService.ts
- packages/workspace-core/src/lib/classes/urlHandlerService.ts
- packages/workspace-core/src/lib/classes/workspaceMediator.ts
- packages/workspace-core/src/lib/tests/observe.spec.ts
- packages/workspace-core/src/lib/types/compare.ts
- packages/workspace-core/src/lib/types/index.ts
- packages/workspace-fusion/src/lib/classes/fusionUrlHandler.ts
- packages/workspace-fusion/src/lib/classes/fusionWorkspaceBuilder.tsx
- packages/workspace-fusion/src/lib/hooks/useMediatorContext.ts
- packages/workspace-fusion/src/lib/utils/addConfig.ts
- packages/workspace-fusion/src/lib/utils/addViewController.ts
- packages/workspace-fusion/src/lib/utils/index.ts
- packages/workspace-react/src/lib/classes/filterController.ts
- packages/workspace-react/src/lib/classes/stateController.ts
- packages/workspace-react/src/lib/classes/tabController.ts
- packages/workspace-react/src/lib/components/tabNavigation/TabNavigation.tsx
-   [x] This change requires a documentation update …
> Fusion URL handler

- .eslintrc.json
- package-lock.json
- package.json
Add tsdoc formatting rule to eslint
-   [ ] My code is easy to read.
-   [ ] Documentation and …
> tsdoc eslint rule

- .eslintrc.json
> add basic eslint rules

- .eslintrc.json
> Improve eslint rules

- packages/workspace-fusion/src/lib/utils/viewController/addViewController.ts
- packages/workspace-react/src/lib/hooks/useEffectOnce.ts
- packages/workspace-react/src/lib/hooks/useMounted.ts
Borrowed a hook from AG-Grid to fix mount/unmount events in workspace view controller
-   [ ] My …
> Fix React 18 useEffect mount events

- packages/test-app/src/app/HandoverApp.tsx
- packages/workspace-fusion/src/lib/classes/fusionWorkspaceBuilder.tsx
- packages/workspace-fusion/src/lib/utils/dataSource/addDataSource.ts
- packages/workspace-react/src/lib/classes/workspaceReactMediator.ts
- packages/workspace-react/src/lib/classes/workspaceViewController.ts
> Fix multiple api calls

- packages/workspace-fusion/src/lib/utils/garden/configureBookmarkService.ts
In cases where a partial bookmark is stored in IndexedDb it would set selectedNodes to undefined and the application would fail …
> fix bookmark bug garden

- packages/test-app/src/app/HandoverApp.tsx
- packages/workspace-fusion/src/lib/classes/fusionWorkspaceBuilder.tsx
- packages/workspace-fusion/src/lib/types/configuration.ts
- packages/workspace-fusion/src/lib/utils/dataSource/addDataSource.ts
- packages/workspace-fusion/src/lib/utils/dataSource/createFetchFunction.ts
> Fusion data fetch

- packages/handover/project.json
> fix dist folder

- packages/workspace-fusion-modules/src/lib/modules/indexedDbModule/types/payload.ts
- packages/workspace-fusion-modules/src/lib/modules/indexedDbModule/utils/sanitizePayload.ts
> save tab in index db

- packages/handover/tsconfig.json
> extend base tsconfig

- packages/ag-grid/src/lib/classes/gridController.ts
- packages/data-source/src/lib/classes/fetchController.ts
- packages/garden/src/lib/classes/gardenController.ts
- packages/workspace-fusion/src/lib/classes/fusionWorkspaceBuilder.tsx
- packages/workspace-fusion/src/lib/utils/dataSource/addDataSource.ts
- packages/workspace-fusion/src/lib/utils/garden/addGarden.tsx
- packages/workspace-fusion/src/lib/utils/grid/addGrid.tsx
- packages/workspace-fusion/src/lib/utils/viewController/addViewController.ts
- packages/workspace-react/src/lib/classes/workspaceViewController.ts
On Workspace unmount, ensure all controllers are nulled out and memory is released
-   [ ] My code …
> Release memory on unmount

- packages/workspace-fusion/src/lib/utils/garden/addGarden.tsx
- packages/workspace-react/src/lib/components/WorkspaceHeader/WorkspaceHeader.tsx
> Fix garden header

- packages/power-bi/src/lib/classes/powerBiController.ts
- packages/power-bi/src/lib/components/PageNavigation/PageNavigation.tsx
Syncs active pages between controller and embed
-   [x] My code is easy to read.
-   [ ] …
> sync active pages with controller

- packages/workspace-fusion/src/lib/utils/powerBI/addPowerBi.tsx
- packages/workspace-react/src/lib/components/workspaceDataLoader/WorkspaceDataLoader.tsx
- packages/workspace-react/src/lib/types/tab.ts
Lets tabs opt out of loading optionally
-   [ ] My code is easy to read.
-   [ ] Documentation and …
> opt out of loading

- packages/workspace-react/src/lib/components/tabNavigation/TabNavigation.tsx
Only render tab navigation in header if there is more than 1 tab to choose from
-   [x] My code is …
> Only render tab navigation if more than 1 tab

- .eslintrc.json
Interfaces does not play well with Record<PropertyKey,unknown>. We use a lot of generics in this project. I suggest preferring types
-   [ ] I have linked …
> [Eslint] Prefer types rule

- packages/ag-grid/src/lib/hooks/useColumnState.ts
Completes: [AB#32699](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/32699)
-   [ ] My code follows the style guidelines of this …
> fix referential unstability

- packages/ag-grid/src/index.ts
- packages/ag-grid/src/lib/components/Grid.tsx
- packages/ag-grid/src/lib/components/ReactGrid.tsx
- packages/ag-grid/src/lib/components/index.ts
- packages/ag-grid/src/lib/types/gridConfig.ts
- packages/ag-grid/src/lib/types/index.ts
Completes: [AB#32723](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/32723)
-   [ ] My code follows the style guidelines of this …
> create react grid

- commitlint.config.js
- lerna.json
- package-lock.json
- package.json
Completes: 
[AB#32745](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/32745)
[AB#32746](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/32746)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please …
> Add husky and lerna

- packages/data-source/package.json
- packages/workspace-fusion/package.json
- pnpm-lock.yaml
> chore(release): :bookmark: release data source v.0.0.2

- packages/ag-grid/package.json
- packages/data-source/package.json
- packages/filter/package.json
- packages/garden/package.json
- packages/observable-proxy/package.json
- packages/power-bi/package.json
- packages/sidesheet/package.json
- packages/status-bar/package.json
- packages/workspace-core/package.json
- packages/workspace-fusion-modules/package.json
- packages/workspace-fusion/package.json
- packages/workspace-react/package.json
Completes: [AB#33283](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33283) …
> chore: update publish config for all packages

- packages/workspace-fusion/src/index.ts
- pnpm-lock.yaml
> fix: export workspace from workspace-fusion

- packages/ag-grid/package.json
- packages/data-source/src/lib/classes/fetchController.ts
- packages/power-bi/src/lib/components/Filter/Filter.tsx
- packages/workspace-core/package.json
- packages/workspace-core/src/lib/classes/observable.ts
- packages/workspace-react/src/lib/components/workspaceDataLoader/WorkspaceDataLoader.tsx
- pnpm-lock.yaml
Completes: [AB#33285](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33285) …
> fix: trigger release

- package.json
Completes: [AB#33291](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33291) …
> chore: add release scripts

- packages/status-bar/package.json
- packages/status-bar/src/lib/components/StatusBar.tsx
- pnpm-lock.yaml
Completes: [AB#33302](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33302) …
> Re release/status bar

- .github/workflows/release.yml
Completes: [AB#33308](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33308) …
> build: :bookmark: release pipeline

- packages/workspace-fusion/src/index.ts
Completes: [AB#33309](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33309) …
> chore: export gardenconfig and filterconfig

- packages/filter/src/lib/components/Filter.tsx
- packages/garden/src/lib/components/Garden.tsx
- packages/power-bi/src/lib/components/PowerBi.tsx
- packages/workspace-fusion/src/index.ts
- packages/workspace-fusion/src/lib/types/configuration.ts
Completes: [AB#33317](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33317) …
> fix: :bug: fix icons crashing fusion-workspace

- packages/garden/src/lib/classes/gardenController.ts
- packages/garden/src/lib/types/config.ts
- packages/workspace-fusion/src/lib/classes/fusionWorkspaceBuilder.tsx
- packages/workspace-fusion/src/lib/types/configuration.ts
- packages/workspace-fusion/src/lib/utils/garden/addGarden.tsx
Completes: [AB#33309](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33309) …
> Breaking change! ✨ update workspace-fusion config

- packages/workspace-react/src/lib/components/Workspace.tsx
- packages/workspace-react/src/lib/hooks/useSetFallbackTab.ts
> fix: :bug: set fallback tab if none set (workspace-react)

- apps/test-app/index.html
- apps/test-app/package.json
- apps/test-app/src/App.css
- apps/test-app/src/App.tsx
- apps/test-app/src/index.css
- apps/test-app/src/main.tsx
- apps/test-app/tsconfig.json
- apps/test-app/tsconfig.node.json
- apps/test-app/vite.config.ts
- pnpm-lock.yaml
> test: add test app

- .vscode/settings.json
- packages/workspace-react/src/lib/components/Workspace.tsx
> fix(Workspace-react): :bug: fix relative import breaking package

- .vscode/settings.json
- packages/ag-grid/package.json
- packages/ag-grid/tsconfig.lib.json
- packages/data-source/package.json
- packages/data-source/tsconfig.lib.json
- packages/filter/package.json
- packages/filter/tsconfig.lib.json
- packages/garden/package.json
- packages/garden/tsconfig.lib.json
- packages/observable-proxy/tsconfig.json
- packages/power-bi/tsconfig.lib.json
- packages/sidesheet/package.json
- packages/sidesheet/tsconfig.lib.json
- packages/status-bar/tsconfig.lib.json
- packages/workspace-core/tsconfig.lib.json
- packages/workspace-fusion-modules/tsconfig.lib.json
- packages/workspace-fusion/package.json
- packages/workspace-fusion/src/lib/tests/highlightService.spec.ts
- packages/workspace-fusion/tsconfig.lib.json
- packages/workspace-react/package.json
- packages/workspace-react/tsconfig.lib.json
- pnpm-lock.yaml
- tsconfig.base.json
> Refactor tsconfig

- apps/test-app/src/App.tsx
- packages/workspace-fusion/src/lib/utils/createFusionWorkspace.tsx
- pnpm-lock.yaml
> feat: :children_crossing: return component directly

- .vscode/settings.json
- packages/garden/src/lib/components/DefaultGardenItem/DefaultGardenItem.tsx
- packages/garden/src/lib/components/FilterSelector/FilterSelector.tsx
- packages/garden/src/lib/components/HeaderContainer/HeaderContainer.tsx
> chore(garden): :poop: fix garden build errors

- packages/garden/src/lib/components/DefaultGardenItem/DefaultGardenItem.tsx
> chore: fix garden build

- packages/workspace-core/src/lib/classes/workspaceMediator.ts
- packages/workspace-core/src/lib/types/serviceCtor.ts
- packages/workspace-core/src/lib/utils/services/bookmarkService.ts
- packages/workspace-core/src/lib/utils/services/clickService.ts
- packages/workspace-core/src/lib/utils/services/contextService.ts
- packages/workspace-core/src/lib/utils/services/dataService.ts
- packages/workspace-core/src/lib/utils/services/errorService.ts
- packages/workspace-core/src/lib/utils/services/index.ts
- packages/workspace-core/src/lib/utils/services/selectionService.ts
- packages/workspace-core/src/lib/utils/services/urlService.ts
- packages/workspace-fusion/src/lib/hooks/useMediatorAsState.ts
Completes: [AB#33471](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33471) …
> chore: hide destructors from service consumers

- packages/workspace-core/src/lib/utils/services/dataService.ts
> fix: :bug: dataservice lost this scoping

- apps/test-app/src/App.tsx
- packages/workspace-fusion/src/lib/components/Sidesheet/SidesheetWrapper.tsx
- packages/workspace-fusion/src/lib/integrations/sidesheet/sidesheet.ts
- packages/workspace-fusion/src/lib/utils/createWorkspaceConfig.ts
- packages/workspace-fusion/src/lib/utils/sidesheet/addSidesheet.tsx
> chore: rework sidesheet to always give id

- packages/ag-grid/src/lib/components/ReactGrid.tsx
- packages/ag-grid/src/lib/utils/createGridController.ts
- packages/workspace-fusion/src/lib/utils/grid/addGrid.tsx
Completes: [AB#33630](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33630) …
> chore: protect destroy method of grid

- packages/sidesheet/src/lib/utils/createSidesheet.tsx
> chore: sidesheet workaround

- packages/ag-grid/src/ag-grid-styling/styles/gridStyles.css.ts
- packages/ag-grid/src/ag-grid-styling/styles/pagination/agPagingPanel.ts
Completes: [AB#33834](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33834) …
> style: :lipstick: remove pagination top border

- packages/garden/src/lib/classes/gardenController.ts
> fix: :bug: fix custom description not working

- packages/power-bi/src/lib/components/PowerBi.tsx
> fix: :bug: powerbi height issue

- packages/filter/src/lib/components/quickFilter/QuickFilter.tsx
- packages/garden/src/lib/components/VirtualContainer/VirtualContainer.tsx
- packages/status-bar/src/lib/components/StatusBar.tsx
- packages/workspace-fusion/src/lib/components/TabNavigation/TabNavigation.tsx
- packages/workspace-fusion/src/lib/integrations/grid/components/wrapper/GridWrapper.tsx
- packages/workspace-react/src/lib/components/Workspace.tsx
- packages/workspace-react/src/lib/components/WorkspaceHeader/WorkspaceHeader.tsx
- packages/workspace-react/src/lib/components/workspaceBody/WorkspaceBody.tsx
- packages/workspace-react/src/lib/components/workspaceTab/WorkspaceTab.tsx
Completes: [AB#33855](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33855) …
> chore: add div ids to main components

- packages/workspace-react/src/lib/components/WorkspaceHeader/WorkspaceHeader.tsx
Completes: [AB#33861](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33861) …
> fix: :bug: workspace filter width overflow

- apps/test-app/src/App.tsx
- packages/workspace-fusion/src/lib/integrations/grid/grid.ts
- packages/workspace-fusion/src/lib/integrations/grid/utils/setConfigOnController.ts
Completes: [AB#33872](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33872)
Closes #226 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
> feat: :sparkles: ag grid pagination by default

- packages/garden/src/lib/utils/createGarden.ts
Completes: [AB#33878](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33878)
Closes #222 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
> fix: :bug: collapseSubgroupsByDefault opposite

- packages/workspace-fusion/src/lib/hooks/useFilteredData.ts
- packages/workspace-fusion/src/lib/integrations/status-bar/components/StatusBarWrapper.tsx
Completes: [AB#33880](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33880)
Closes #224 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
> fix: :bug: status bar showing n/a when data undefined

- packages/workspace-fusion/src/lib/utils/viewController/addViewController.tsx
Completes: [AB#33894](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33894)
Closes #233 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
> fix: :bug: loading default tab when query param is present

- .vscode/settings.json
- README.md
> docs: :memo: update readme project

- packages/workspace-fusion/src/lib/integrations/sidesheet/components/wrapper/SidesheetSimpleWrapper.tsx
- packages/workspace-fusion/src/lib/integrations/sidesheet/sidesheet.ts
Closes: #251
-   [ ] My code follows the style guidelines of …
> fix: :bug: add controller to simple sidesheet

- packages/workspace-fusion/src/lib/integrations/sidesheet/sidesheet.ts
Closes: #250
-   [ ] My code follows the style guidelines of …
> fix: :bug: mandatory generics in sidesheet config

- apps/test-app/package.json
- packages/garden/package.json
- packages/garden/src/lib/classes/gardenController.ts
- packages/garden/src/lib/components/FilterSelector/FilterSelector.tsx
- packages/garden/src/lib/hooks/useData.ts
- packages/garden/src/lib/utils/createGarden.ts
- packages/garden/src/lib/utils/createGardenProp.ts
- packages/workspace-fusion/src/lib/integrations/garden/utils/configureDataChange.ts
- packages/workspace-react/src/lib/hooks/useControllerContext.ts
- pnpm-lock.yaml
> chore: replace reactiveValue with rxjs

- packages/workspace-fusion/src/lib/integrations/sidesheet/components/wrapper/SidesheetSimpleWrapper.tsx
> fix: :bug: sidesheet close

- packages/filter/src/lib/components/expandedFilterGroup/ExpandedFilterGroup.tsx
- packages/filter/src/lib/components/expandedFilterGroup/expandedFilterGroup.styles.ts
> fix: :bug: fix icon overflow

- packages/garden/src/lib/components/FilterSelector/FilterSelector.tsx
- packages/garden/src/lib/components/FilterSelector/filterSelector.styles.ts
> refactor: :recycle: refactor common pitfalls

- packages/workspace-fusion/src/lib/classes/fusionUrlHandler.ts
- packages/workspace-fusion/src/lib/utils/viewController/addViewController.tsx
> chore: remove history changes when navigating

- packages/workspace-fusion/src/lib/components/Workspace.tsx
- packages/workspace-fusion/src/lib/integrations/data-source/context/QueryContext.tsx
- packages/workspace-fusion/src/lib/integrations/data-source/types/index.ts
- packages/workspace-fusion/src/lib/integrations/data-source/utils/createFetchFunction.ts
- packages/workspace-fusion/src/lib/integrations/data-source/utils/prepareConfig.ts
Necessary for using initialData
> feat: :sparkles: make getResponseAsync optional

- packages/workspace-fusion/src/lib/components/NoDataSplashScreen.tsx
> fix: :bug: fix no data splash screen not showing

- apps/test-app/src/App.tsx
- packages/workspace-fusion/src/lib/components/Workspace.tsx
- packages/workspace-fusion/src/lib/context/WorkspaceHeaderComponents.tsx
- packages/workspace-fusion/src/lib/integrations/common/components/TabNavigation.tsx
- packages/workspace-fusion/src/lib/integrations/data-source/context/QueryContext.tsx
- packages/workspace-fusion/src/lib/integrations/data-source/utils/prepareConfig.ts
- packages/workspace-fusion/src/lib/integrations/power-bi/components/PowerBiPopover.tsx
- packages/workspace-fusion/src/lib/integrations/power-bi/power-bi.ts
- packages/workspace-fusion/src/lib/integrations/power-bi/utils/addPowerBi.tsx
> feat: :sparkles: add popover to powerbi

- packages/workspace-fusion/src/lib/integrations/power-bi/components/PowerBiPopover.tsx
- packages/workspace-fusion/src/lib/integrations/power-bi/power-bi.ts
> fix: :bug: fix powerbi popover close

- packages/power-bi/src/lib/components/QuickFilter/QuickFilter.tsx
> style: :lipstick: add padding to filter

- packages/workspace-fusion/src/lib/integrations/common/components/TabNavigation.tsx
> style: :lipstick: fix dividers occuring when there are no siblings

- packages/filter/package.json
- packages/filter/src/lib/components/expandedFilterGroup/expandedFilterGroup.styles.ts
- packages/filter/src/lib/components/filterView/filterView.styles.ts
- pnpm-lock.yaml
> chore: :arrow_up: update deps

- packages/ag-grid/package.json
- pnpm-lock.yaml
> chore: :arrow_up: upgrade deps in ag-grid

- packages/power-bi/package.json
- pnpm-lock.yaml
> chore: :arrow_up: update deps powerbi

- packages/sidesheet/package.json
- pnpm-lock.yaml
> chore: :arrow_up: upgrade sidesheet deps

- packages/observable-proxy/package.json
- pnpm-lock.yaml
> chore: :arrow_up: update deps obs proxy

- packages/garden/package.json
- packages/garden/src/lib/components/FilterSelector/FilterSelector.tsx
- packages/garden/src/lib/components/FilterSelector/filterSelector.styles.ts
- pnpm-lock.yaml
> chore: :arrow_up: update garden deps

- packages/workspace-core/package.json
- pnpm-lock.yaml
> chore: :arrow_up: update deps in core

- package.json
- packages/ag-grid/package.json
- packages/filter/package.json
- packages/garden/package.json
- packages/observable-proxy/package.json
- packages/power-bi/package.json
- packages/sidesheet/package.json
- packages/status-bar/package.json
- packages/workspace-core/package.json
- packages/workspace-fusion-modules/package.json
- packages/workspace-fusion/package.json
- packages/workspace-fusion/vite.config.ts
- packages/workspace-react/package.json
- pnpm-lock.yaml
> build: bundle workspace-fusion

- packages/workspace-fusion/package.json
- packages/workspace-fusion/vite.config.ts
- pnpm-lock.yaml
> build: externalize react dep

- apps/dynamic/package.json
- apps/dynamic/server.js
- apps/test-app/package.json
- apps/test-app/src/App.tsx
- apps/test-app/src/main.tsx
- packages/workspace-dynamic/package.json
- packages/workspace-dynamic/src/components/Center.tsx
- packages/workspace-dynamic/src/components/InnerLoader.tsx
- packages/workspace-dynamic/src/hooks/useVersionOverride.ts
- packages/workspace-dynamic/src/index.tsx
- packages/workspace-dynamic/tsconfig.json
- packages/workspace-dynamic/tsconfig.lib.json
- packages/workspace-fusion/package.json
- packages/workspace-fusion/src/index.ts
- packages/workspace-fusion/src/index.tsx
- packages/workspace-fusion/src/plugin.js
- packages/workspace-fusion/src/plugin.ts
- packages/workspace-fusion/vite.config.ts
- pnpm-lock.yaml
> feat: ✨workspace-dynamic

- packages/workspace-dynamic/src/index.tsx
> fix: :bug: add queryClient provider

- apps/test-app/package.json
- apps/test-app/src/main.tsx
- packages/workspace-fusion/src/lib/integrations/garden/components/workspace-header/WorkspaceHeader.tsx
- packages/workspace-fusion/src/lib/integrations/grid/components/workspaceHeader/GridWorkspaceHeader.tsx
> fix: :bug: fix tab placement

- .github/workflows/.deploy.yml
- documentation/astro.config.mjs
> chore: add deploy script to docs

- documentation/src/consts.ts
- documentation/src/content/docs/concepts/boundaries.mdx
- documentation/src/content/docs/concepts/dynamic.mdx
- documentation/src/content/docs/config/grid-options.md
Addresses: 
[AB#36137](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/36137)
[AB#36142](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/36142)
> docs: :memo: add concepts page

- documentation/package.json
- documentation/src/components/Diagram/Diagram.tsx
- pnpm-lock.yaml
> fix: :bug: fix docs mermaid

- documentation/src/content/docs/examples/power-bi-only.md
- packages/workspace-fusion-modules/src/lib/modules/fusionBookmarks/BookmarkModule.tsx
- packages/workspace-fusion/src/lib/context/WorkspaceHeaderComponents.tsx
- packages/workspace-fusion/src/lib/integrations/common/components/TabNavigation.tsx
- packages/workspace-fusion/src/lib/integrations/power-bi/power-bi.ts
- packages/workspace-fusion/src/lib/integrations/power-bi/utils/addPowerBi.tsx
Addresses: [AB#34930](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/34930)
> feat: :sparkles: powerbi classification

- packages/workspace-fusion/src/lib/components/Workspace.tsx
- packages/workspace-fusion/src/lib/components/error/WorkspaceBoundary.tsx
- packages/workspace-fusion/src/lib/components/error/WorkspaceError.tsx
- packages/workspace-fusion/src/lib/components/error/index.ts
- packages/workspace-fusion/src/lib/utils/createWorkspaceConfig.ts
> feat: add error boundary

- .npmrc
- packages/ag-grid/package.json
- packages/filter/package.json
- packages/garden/package.json
- packages/observable-proxy/package.json
- packages/power-bi/package.json
- packages/sidesheet/package.json
- packages/status-bar/package.json
- packages/workspace-core/package.json
- packages/workspace-dynamic/package.json
- packages/workspace-fusion-modules/package.json
- packages/workspace-fusion/package.json
- packages/workspace-fusion/src/lib/components/error/index.ts
- packages/workspace-fusion/src/lib/utils/createWorkspaceConfig.ts
- packages/workspace-fusion/src/modules/garden/components/utils/configureBookmarkService.ts
- packages/workspace-fusion/src/modules/garden/components/utils/configureClickEvents.ts
- packages/workspace-fusion/src/modules/garden/components/utils/configureDataChange.ts
- packages/workspace-fusion/src/modules/garden/components/utils/configureHighlight.ts
- packages/workspace-fusion/src/modules/garden/icons/GardenIcon.tsx
- packages/workspace-fusion/src/modules/garden/index.tsx
- packages/workspace-fusion/src/modules/grid/index.tsx
- packages/workspace-fusion/src/modules/power-bi/index.tsx
- packages/workspace-react/package.json
- pnpm-lock.yaml
> build: add .npmrc

- packages/ag-grid/src/lib/components/Grid.tsx
> feat: :sparkles: show groupname header ag grid

- packages/sidesheet/CHANGELOG.md
- packages/sidesheet/package.json
- packages/sidesheet/src/lib/components/ResizeWrapper.tsx
- packages/workspace-fusion/package.json
- pnpm-lock.yaml
> fix: :bug: fix scroll sidesheet

- packages/filter/CHANGELOG.md
- packages/filter/package.json
- packages/filter/src/lib/components/filterGroup/FilterGroup.tsx
- packages/filter/src/lib/utils/getFilterHeaderText.tsx
- packages/workspace-fusion/CHANGELOG.md
- packages/workspace-fusion/package.json
> fix: :bug: fix quickfilter not showing checked values

- packages/workspace-fusion/src/lib/integrations/status-bar/components/StatusBarWrapper.tsx
- packages/workspace-fusion/src/lib/integrations/status-bar/components/StyledSkeletons.tsx
> style: :lipstick: add loading skeletons to status bar

- packages/filter/package.json
- packages/filter/src/lib/components/expandedFilterGroup/ExpandedFilterGroup.tsx
- packages/filter/src/lib/components/expandedFilterItem/ExpandedFilterItem.tsx
- packages/filter/src/lib/components/filterGroup/FilterGroup.tsx
- packages/filter/src/lib/components/filterGroupPopoverMenu/FilterGroupPopoverMenu.tsx
- packages/filter/src/lib/components/filterItem/FilterItemCheckbox.tsx
- packages/filter/src/lib/components/filterView/FilterView.tsx
- packages/filter/src/lib/components/quickFilter/QuickFilter.tsx
- packages/filter/src/lib/components/skeleton/Skeleton.tsx
- packages/filter/src/lib/components/virtualContainer/VirtualContainer.tsx
- packages/workspace-fusion/package.json
> feat: :sparkles: add loading skeleton filter

- apps/test-app/src/main.tsx
- packages/ag-grid/package.json
- packages/workspace-fusion/CHANGELOG.md
- packages/workspace-fusion/package.json
- packages/workspace-react/CHANGELOG.md
- packages/workspace-react/package.json
- packages/workspace-react/src/lib/components/Workspace.tsx
- pnpm-lock.yaml
> fix: :bug: fix scrollbar bottom of screen

- packages/ag-grid/package.json
- pnpm-lock.yaml
> fix: :bug: try fix license key

- packages/workspace-fusion/CHANGELOG.md
- packages/workspace-fusion/package.json
> chore: :bookmark: release @workspace-fusion@1.0.7

- packages/ag-grid/package.json
- packages/workspace-fusion/package.json
- pnpm-lock.yaml
> fix: :bug: fix ag grid version

- packages/workspace-fusion/src/lib/components/Workspace.tsx
> fix: :bug: fix url query param

- packages/power-bi/src/lib/components/powerbi.styles.ts
> style: :lipstick: powerbi scrollbar

- packages/power-bi/CHANGELOG.md
- packages/power-bi/package.json
- packages/power-bi/src/lib/components/powerbi.styles.ts
- packages/workspace-fusion/CHANGELOG.md
- packages/workspace-fusion/package.json
> chore: release

- packages/garden/src/lib/components/GardenItemContainer/GardenItemContainer.tsx
- packages/workspace-fusion/package.json
- packages/workspace-fusion/src/lib/classes/fusionUrlHandler.tsx
- packages/workspace-fusion/src/lib/components/Workspace.tsx
- packages/workspace-react/package.json
- packages/workspace-react/src/lib/components/Workspace.tsx
- packages/workspace-react/src/lib/components/workspaceBody/WorkspaceBody.tsx
- pnpm-lock.yaml
> fix: :bug: fix sidesheet closing on first render

- packages/filter/package.json
- packages/filter/src/lib/components/filterQuickSearch/FilterQuickSearch.tsx
- packages/workspace-fusion/package.json
- packages/workspace-fusion/src/lib/integrations/filter/filter.ts
Fixes search visual state clears between tabchanges while search state does not.
Also exported unexported type
> fix: :bug: fix search clearing between tabchange

- packages/filter/package.json
- packages/filter/src/lib/components/filterQuickSearch/FilterQuickSearch.tsx
- packages/garden/package.json
- packages/garden/src/lib/components/Garden.tsx
- packages/workspace-fusion/package.json
- packages/workspace-fusion/src/modules/garden/components/GroupingSelector.tsx
Fixes dropdown not working as intended in garden popover
Fixes search not clearing when clicking the "x" button
#415 
> fix: garden input not updating

- packages/ag-grid/package.json
- packages/ag-grid/src/lib/components/ClientGrid.tsx
- packages/ag-grid/src/lib/components/Grid.tsx
- packages/ag-grid/src/lib/components/ServerGrid.tsx
> feat:expose-grid-settings

- packages/workspace-fusion/package.json
- packages/workspace-fusion/src/lib/integrations/sidesheet/components/wrapper/SidesheetSimpleWrapper.tsx
> fix: :bug: remove onError close in sidesheet

- packages/filter/src/lib/components/skeleton/Skeleton.tsx
- packages/garden/src/lib/components/VirtualGarden/VirtualGarden.tsx
- packages/garden/src/lib/components/gardenSkeleton/GardenSkeleton.tsx
- packages/power-bi/src/lib/components/QuickFilter/QuickFilter.tsx
- packages/workspace-core/src/lib/classes/workspaceMediator.ts
- packages/workspace-fusion/src/lib/classes/fusionUrlHandler.tsx
- packages/workspace-fusion/src/lib/components/Workspace.tsx
- packages/workspace-fusion/src/lib/integrations/garden/types/workspaceProps.ts
- packages/workspace-fusion/src/lib/integrations/sidesheet/components/addSidesheet.tsx
- packages/workspace-fusion/src/lib/integrations/sidesheet/components/wrapper/SidesheetAdvancedWrapper.tsx
- packages/workspace-fusion/src/lib/integrations/sidesheet/components/wrapper/SidesheetSimpleWrapper.tsx
- packages/workspace-fusion/src/lib/integrations/sidesheet/sidesheet.ts
- packages/workspace-fusion/src/lib/integrations/sidesheet/types/workspaceProps.ts
- packages/workspace-fusion/src/lib/integrations/status-bar/components/StatusBarWrapper.tsx
- packages/workspace-fusion/src/lib/integrations/status-bar/components/StyledSkeletons.tsx
- packages/workspace-fusion/src/lib/integrations/status-bar/utils/addStatusBar.tsx
- packages/workspace-fusion/src/lib/types/event.ts
- packages/workspace-fusion/src/lib/types/fusionController.ts
- packages/workspace-fusion/src/lib/types/workspaceProps.ts
- packages/workspace-fusion/src/lib/utils/createWorkspaceConfig.tsx
- packages/workspace-fusion/src/modules/garden/components/workspace-header/WorkspaceHeader.tsx
- packages/workspace-fusion/src/modules/garden/components/wrapper/GardenWrapper.tsx
- packages/workspace-fusion/src/modules/grid/components/GridWrapper.tsx
- packages/workspace-react/src/lib/components/WorkspaceHeader/WorkspaceHeader.tsx
no longer 24px spacing top. Now it is 5px spacing top
> chore: :lipstick: update menu for workspace spacing

- packages/ag-grid/package.json
- packages/ag-grid/src/index.ts
- packages/workspace-fusion/package.json
- packages/workspace-fusion/src/lib/integrations/grid/grid.ts
- packages/workspace-fusion/src/modules/grid/components/GridWrapper.tsx
> feat: :sparkles: add modules to gridoptions

- packages/workspace-fusion/package.json
- packages/workspace-fusion/src/lib/integrations/grid/index.ts
> chore: export ag grid modules

- apps/test-app/package.json
- packages/filter/package.json
- packages/filter/src/lib/components/filterGroup/FilterGroup.tsx
- packages/filter/src/lib/components/filterGroupPopoverMenu/FilterGroupPopoverMenu.tsx
- packages/workspace-fusion/package.json
> fix(filter): quickfilter flickering

- .github/workflows/ci.yml
> ci: :green_heart: add cache to pnpm in github action

- apps/test-app/src/index.tsx
- packages/filter/package.json
- packages/filter/src/lib/components/expandedFilterItem/ExpandedFilterItem.tsx
- packages/filter/src/lib/components/filterGroup/FilterGroup.tsx
- packages/filter/src/lib/components/filterGroupPopoverMenu/FilterGroupPopoverMenu.tsx
- packages/workspace-fusion/package.json
> fix: :bug: filter item clickable when only one item in group

- packages/power-bi/package.json
- packages/power-bi/src/lib/components/filterItems/FilterItems.tsx
- packages/power-bi/src/lib/components/quickFilterGroup/QuickFilterGroup.tsx
- packages/power-bi/src/lib/types/filter.ts
- packages/workspace-fusion/package.json
> fix: :bug: fix powerbi filter crashing when value is null

- packages/garden/package.json
- packages/workspace-fusion/package.json
> chore: :bookmark: bump versions in garden and workspace

- packages/power-bi/package.json
- packages/power-bi/src/lib/components/expandedFilter/ExpandedFilter.tsx
- packages/workspace-fusion/package.json
> fix: :bug: fix powerbi filters crashing

- packages/power-bi/package.json
- packages/power-bi/src/lib/components/powerbi.styles.ts
- packages/workspace-fusion/package.json
added scrollbar-gutter to fix scroll flickering
> fix: :bug: powerbi scrollbar flickering

- apps/test-app/src/index.tsx
- packages/filter/package.json
- packages/filter/src/lib/components/filterView/filterView.styles.ts
- packages/workspace-fusion/package.json
removed "scroll-bar" height css fixed the issue
> fix: :bug: Missing scroll bar in expanded filter 

- packages/ag-grid/package.json
- packages/power-bi/package.json
- packages/power-bi/src/lib/components/filterItems/filterItems.styles.ts
- packages/workspace-fusion/package.json
- packages/workspace-fusion/src/modules/grid/components/GridWrapper.tsx
Lets you copy text from the grid
> feat: :sparkles: ag grid cell selection

- packages/power-bi/package.json
- packages/power-bi/src/lib/hooks/useVisibleFilterGroups.ts
- packages/workspace-fusion/package.json
Apparently json.parse(undefined) crashes fatally
> fix: json parse undefined

- .github/helpers/src/publish-comment.ts
- .github/workflows/pr-issue-check.yml
The issue checker lacks permission to read issues related to a pr. This is currently a limitation in Github
> disable issue checker

- packages/filter/package.json
- packages/filter/src/lib/components/quickFilter/QuickFilter.tsx
- packages/filter/src/lib/components/quickFilter/quickFilter.styles.ts
- packages/workspace-fusion/package.json
> fix: :bug:  Advanced filter button dissapears

- packages/filter/package.json
- packages/filter/src/lib/components/quickFilter/QuickFilter.tsx
- packages/filter/src/lib/components/toggleHideFilterPopover/ToggleHideFilterPopover.tsx
- packages/workspace-fusion/package.json
> fix/ Filter types order does not reflect current order.

- CONTRIBUTING.md
- README.md
Refactored CONTRIBUTING file
Added badges to README.md
Link to issue: https://github.com/equinor/lighthouse/issues/550
> docs: 📜 SCM Compliance changes

- packages/ag-grid/package.json
- packages/workspace-fusion/package.json
- pnpm-lock.yaml
Link to issue: https://github.com/equinor/lighthouse/issues/554
> fix react version

- packages/power-bi/package.json
- packages/power-bi/src/lib/components/filterItem/filterItem.styles.ts
- packages/power-bi/src/lib/components/filterItemCheckbox/filterItemCheckbox.styles.ts
- packages/power-bi/src/lib/components/filterItems/filterItems.styles.ts
- packages/power-bi/src/lib/components/toggleHideFilterPopover.tsx/ToggleHideFilterPopover.tsx
- packages/power-bi/src/lib/components/virtualList/VirtualList.tsx
- packages/workspace-fusion/package.json
- pnpm-lock.yaml
> fix: powerbi styling issues

- packages/power-bi/package.json
- packages/power-bi/src/lib/components/PowerBi.tsx
- packages/power-bi/src/lib/components/report/Report.tsx
- packages/workspace-fusion/package.json
1. Getting some complaints from customer that the reports are loading slowly
2. Make it fast
3. profit??
> feat: attempted performance improvements powerbi

- .github/actions/pnpm-setup/action.yaml
> ci: fix failing pnpm setup

- packages/workspace-fusion/package.json
Bump version after conflict
Link to issue:
https://github.com/equinor/cc-components/issues/1035
> [!TIP]
> You can test your changes on the test-application. You can find it under apps\test-app\src\index.tsx
> [!CAUTION]
> ⛔ I understand by merging my PR, the changed packages will be published to NPM immediately ⛔
> Bump version

- packages/filter/package.json
- packages/filter/src/lib/components/quickFilter/QuickFilter.tsx
- packages/filter/src/lib/components/quickFilter/quickFilter.styles.ts
- packages/filter/src/lib/components/toggleHideFilterPopover/toggleHideFilterPopover.styles.ts
- packages/workspace-fusion/package.json
Update expand filter button to make it clear that there are more filters than the quick filters
Link to issue:
https://github.com/equinor/fusion-workspace/issues/519
> [!TIP]
> You can test your changes on the test-application. You can find it under apps\test-app\src\index.tsx
> [!CAUTION]
> ⛔ I understand by merging my PR, the changed packages will be published to NPM immediately ⛔
Closes #519
> feat: Update expand filter button
